name: seat_cushion
description: "Seat Cushion."
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: any
  provider: any
  simple_3d: any
  simple_3d_renderer: any
  stream_utils: any
  synchronized: any
  util_simple_3d: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  copy_with_extension_gen: any
  flutter_lints: any
  json_serializable: any

flutter:
  uses-material-design: true
  generate: true

resolution: workspace