name: data_presentation_example
description: "Data Presentation Example."
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  data_presentation: any
  provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

resolution: workspace
